# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-24 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='商品分类名称')),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
            ],
            options={
                'verbose_name': '商品分类',
                'verbose_name_plural': '商品分类',
            },
        ),
    ]
