# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-26 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goods_goodsext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=64, verbose_name='商品分类'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='create_time',
            field=models.DateField(verbose_name='商品添加时间'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='desc',
            field=models.TextField(verbose_name='商品详情描述'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='商品图片'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(max_length=64, verbose_name='商品名称'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.FloatField(default=0, verbose_name='商品价格'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='store',
            field=models.IntegerField(default=0, verbose_name='商品剩余库存'),
        ),
    ]
