# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-26 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_auto_20180226_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.IntegerField(default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='status',
            field=models.IntegerField(default=1, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='goodsext',
            name='status',
            field=models.IntegerField(default=1, verbose_name='状态'),
        ),
    ]
