# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-01 17:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20180302_0126'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('goods', '0006_auto_20180228_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsBuied',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0, verbose_name='价格')),
                ('num', models.IntegerField(default=0, verbose_name='数量')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Goods', verbose_name='商品')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=0, verbose_name='总价格')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='下单时间')),
                ('remark', models.TextField(verbose_name='备注')),
                ('pay_type', models.IntegerField(default=0, verbose_name='付款方式')),
                ('pay_status', models.IntegerField(default=0, verbose_name='付款状态')),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(default=0, verbose_name='状态')),
                ('invoice_type', models.IntegerField(default=0, verbose_name='发票类型')),
                ('invoice_title', models.CharField(max_length=256, verbose_name='发票抬头')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
                ('user_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.UserAddress', verbose_name='收货人')),
            ],
            options={
                'verbose_name_plural': '订单',
                'verbose_name': '订单',
            },
        ),
        migrations.AddField(
            model_name='goodsbuied',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.Order', verbose_name='订单'),
        ),
    ]
