# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-28 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180124_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userext',
            name='verification_time',
            field=models.IntegerField(default=1517121461.105882),
        ),
    ]
