# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-29 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20180128_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='userext',
            name='sex',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userext',
            name='verification_time',
            field=models.IntegerField(default=1517225358.14845),
        ),
    ]
