# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-07 04:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0005_auto_20180129_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('addr', models.CharField(max_length=256)),
                ('telephone', models.CharField(max_length=32)),
                ('fiexedphone', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='userext',
            name='verification_time',
            field=models.IntegerField(default=1517978412.8756287),
        ),
    ]
