# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-07 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20180207_1230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='fiexedphone',
            new_name='fixedphone',
        ),
        migrations.AlterField(
            model_name='userext',
            name='verification_time',
            field=models.IntegerField(default=1517989049.983182),
        ),
    ]
