# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-24 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20180207_1527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraddress',
            options={'verbose_name': '用户收获地址信息', 'verbose_name_plural': '用户收获地址信息'},
        ),
        migrations.AlterModelOptions(
            name='userext',
            options={'verbose_name': '用户信息', 'verbose_name_plural': '用户信息'},
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='addr',
            field=models.CharField(max_length=256, verbose_name='收获地址'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='收货人邮箱'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='fixedphone',
            field=models.CharField(max_length=32, verbose_name='收货人固定电话'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='name',
            field=models.CharField(max_length=64, verbose_name='收货人'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='status',
            field=models.IntegerField(default=1, verbose_name='收获地址状态'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='telephone',
            field=models.CharField(max_length=32, verbose_name='收货人电话'),
        ),
        migrations.AlterField(
            model_name='userext',
            name='avatar',
            field=models.CharField(max_length=256, verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='userext',
            name='birthday',
            field=models.DateField(verbose_name='生日'),
        ),
        migrations.AlterField(
            model_name='userext',
            name='logintime',
            field=models.DateTimeField(verbose_name='登陆时长'),
        ),
        migrations.AlterField(
            model_name='userext',
            name='nickname',
            field=models.CharField(max_length=64, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='userext',
            name='realname',
            field=models.CharField(max_length=64, verbose_name='真实名称'),
        ),
        migrations.AlterField(
            model_name='userext',
            name='score',
            field=models.IntegerField(default=0, verbose_name='积分'),
        ),
        migrations.AlterField(
            model_name='userext',
            name='sex',
            field=models.IntegerField(default=1, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='userext',
            name='status',
            field=models.IntegerField(default=0, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='userext',
            name='telephone',
            field=models.CharField(max_length=32, verbose_name='移动电话'),
        ),
        migrations.AlterField(
            model_name='userext',
            name='validkey',
            field=models.CharField(max_length=256, verbose_name='验证码'),
        ),
        migrations.AlterField(
            model_name='userext',
            name='verification_time',
            field=models.IntegerField(default=1519446803.7862716, verbose_name='失效时间'),
        ),
    ]
