# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-26 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20180226_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userext',
            name='verification_time',
            field=models.IntegerField(default=1519631863.9413052, verbose_name='失效时间'),
        ),
    ]
