# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-26 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_auto_20180226_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userext',
            name='verification_time',
            field=models.IntegerField(default=1519660465.1129417, verbose_name='失效时间'),
        ),
    ]
