# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-28 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20180226_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userext',
            name='verification_time',
            field=models.IntegerField(default=1519831149.5103455, verbose_name='失效时间'),
        ),
    ]
