# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-28 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20180228_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userext',
            name='verification_time',
            field=models.IntegerField(default=1519838114.2917387, verbose_name='失效时间'),
        ),
    ]
