# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-28 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_auto_20180301_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userext',
            name='verification_time',
            field=models.IntegerField(default=1519838857.3949723, verbose_name='失效时间'),
        ),
    ]
