# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-01 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_auto_20180301_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userext',
            name='verification_time',
            field=models.IntegerField(default=1519925817.6907465, verbose_name='失效时间'),
        ),
    ]
