# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-11 04:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20180302_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userext',
            name='verification_time',
            field=models.IntegerField(default=1520743480.752194, verbose_name='失效时间'),
        ),
    ]
